kit:
  name: In-Stream Processing Blueprint reference implementation deployment support kit
  link: https://github.com/shinjik/instream-deployment-scripts
  applications:
    - name: "Mesos cluster"
      manifest: https://raw.github.com/shinjik/instream-deployment-scripts/master/manifests/mesos-cluster.yml
    - name: "Mesos/Marathon Manager"
      manifest: https://raw.github.com/shinjik/instream-deployment-scripts/master/manifests/manager.yml
    - name: "Scripting Service"
      manifest: https://raw.github.com/shinjik/instream-deployment-scripts/master/manifests/scripting-service.yml
    - name: "In-stream environment on marathon"
      manifest: https://raw.github.com/shinjik/instream-deployment-scripts/master/manifests/environment.yml
    - name: "In-stream environment on marathon Factory"
      manifest: https://raw.github.com/shinjik/instream-deployment-scripts/master/manifests/environment-factory.yml
    - name: "ISP web UI on marathon"
      manifest: https://raw.github.com/shinjik/instream-deployment-scripts/master/manifests/webui.yml
    - name: "ISP web UI on marathon Factory"
      manifest: https://raw.github.com/shinjik/instream-deployment-scripts/master/manifests/webui-factory.yml
    - name: "Cassandra on marathon"
      manifest: https://raw.github.com/shinjik/instream-deployment-scripts/master/manifests/cassandra.yml
    - name: "Cassandra on marathon Factory"
      manifest: https://raw.github.com/shinjik/instream-deployment-scripts/master/manifests/cassandra-factory.yml
    - name: "Kafka on marathon"
      manifest: https://raw.github.com/shinjik/instream-deployment-scripts/master/manifests/kafka.yml
    - name: "Kafka on marathon Factory"
      manifest: https://raw.github.com/shinjik/instream-deployment-scripts/master/manifests/kafka-factory.yml
    - name: "Marathon Application"
      manifest: https://raw.github.com/shinjik/instream-deployment-scripts/master/manifests/marathon-application.yml
    - name: "Marathon Application Factory"
      manifest: https://raw.github.com/shinjik/instream-deployment-scripts/master/manifests/marathon-application-factory.yml
    - name: "Redis on marathon"
      manifest: https://raw.github.com/shinjik/instream-deployment-scripts/master/manifests/redis.yml
    - name: "Redis on marathon Factory"
      manifest: https://raw.github.com/shinjik/instream-deployment-scripts/master/manifests/redis-factory.yml
    - name: "Zookeeper on marathon"
      manifest: https://raw.github.com/shinjik/instream-deployment-scripts/master/manifests/zookeeper.yml
    - name: "Zookeeper on marathon Factory"
      manifest: https://raw.github.com/shinjik/instream-deployment-scripts/master/manifests/zookeeper-factory.yml
    - name: "Spark on marathon"
      manifest: https://raw.github.com/shinjik/instream-deployment-scripts/master/manifests/spark.yml
    - name: "Spark on marathon Factory"
      manifest: https://raw.github.com/shinjik/instream-deployment-scripts/master/manifests/spark-factory.yml
    - name: "Docker Service"
      manifest: https://raw.github.com/qubell-bazaar/docker/master/docker.yml
    - name: "Scripting Service on Docker"
      manifest: https://raw.github.com/qubell-bazaar/component-docker-scripting/master/scripting.yml

  provider:
    name: Grid Dynamics
    link: https://griddynamics.com
  documentation:
    overview: |
      This kit contains set of manifests and deployment scripts to provide support for the following elements of reference implementation for In-Stream Processing Blueprint:
      * Mesos/Marathon cluster
      * Scripting service with set of scripts to support management of Docker containers over Mesos/Marathon
      * Set of Factories and Components for key components of In-Stream processing service implementation
