---
#
# Host hash playbook
#

- hosts: localhost
  connection: local
  sudo: yes
  roles:
    - role: ../../
      zookeeper_hosts:
        - host: "{{inventory_hostname}}" # the machine running
          id: 2

- hosts: localhost
  connection: local
  sudo: yes
  gather_facts: false
  tasks:
      # Expecting myid to be 2 as defined in zookeeper_hosts variable
    - shell: "grep 2 /var/lib/zookeeper/myid"
      register: status
      failed_when: status.rc != 0
