---
#
# Host list playbook
#

- hosts: localhost
  connection: local
  sudo: yes
  roles:
    - role: ../../
      zookeeper_hosts:
        - "{{inventory_hostname}}"

- hosts: localhost
  connection: local
  sudo: yes
  gather_facts: false
  tasks:
      # Expecting myid to be 1 defined by loop.index
    - shell: "grep 1 /var/lib/zookeeper/myid"
      register: status
      failed_when: status.rc != 0
