application:
  configuration:
    configuration.name: '/new-cassandra'
    configuration.jmx-port: 31916
    configuration.internode-communication-port: 31700
    configuration.tls-internode-communication-port: 31702
    configuration.thrift-client-port: 31199
    configuration.cql-native-port: 31942
  interfaces:
    configuration:
      "*": bind(application#configuration.*)
    cassandra:
      "*": bind(application#cassandra.*)
    compute:
      "*": bind(application#compute.*)
    control:
      "*": bind(application#control.*)
  components:
    application:
      type: scripted.Component
      configuration:
        factory.name: Cassandra on marathon Factory
        factory.launchScript:           /cassandra/create.py
        factory.destroyScript:          /cassandra/destroy.py
        factory.healthCheckScript:      /cassandra/healthCheck.py
        factory.reconfigurationScript:  /cassandra/reconfigure.py
        factory.commandScripts:
          control.restart:              /cassandra/restart.py
          control.scale:                /cassandra/scale.py
      interfaces:
        configuration:
          name:
            type: configuration(string)
            name: Application name
          jmx-port:
            type: configuration(int)
            name: JMX port
          internode-communication-port:
            type: configuration(int)
            name: Internode communication port
          tls-internode-communication-port:
            type: configuration(int)
            name: TLS internode communication port
          thrift-client-port:
            type: configuration(int)
            name: Thrift client port
          cql-native-port:
            type: configuration(int)
            name: CQL native port
        cassandra:
          seed-hosts:
            type: publish-signal(list<string>)
            name: Seed host
          node-hosts:
            type: publish-signal(list<string>)
            name: Node hosts
          jmx-port:
            type: publish-signal(string)
            name: JMX port
          internode-communication-port:
            type: publish-signal(string)
            name: Internode communication port
          tls-internode-commucation-port:
            type: publish-signal(string)
            name: TLS internode communication port
          thrift-client-port:
            type: publish-signal(string)
            name: Thrift client port
          cql-native-port:
            type: publish-signal(string)
            name: CQL native port
        compute:
          ram:
            type: publish-signal(string)
            name: RAM
          cpu:
            type: publish-signal(string)
            name: CPU
          disk:
            type: publish-signal(string)
            name: Disk
        control:
          restart:
            type: receive-command()
            name: Restart
          scale:
            type: receive-command(int instances)
            name: Scale cluster
            arguments:
              instances:
                name: Cluster node size
                default: 1
