---
language: python
python: "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install curl -y

install:
  - pip install -U ansible

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  # Check the role/playbook's syntax.
  - "ansible-playbook -i ci/inventory ci/playbook.yml --syntax-check"

  # Run the ansible ci playbook
  - "ansible-playbook -i ci/inventory ci/playbook.yml --connection=local --sudo -vvvv"

  # Run the ansible hosts list
  - "ansible-playbook -i ci/inventory ci/hosts_list.yml --connection=local --sudo -vvvv"

  # Run the ansible hosts hash
  - "ansible-playbook -i ci/inventory ci/hosts_hash.yml --connection=local --sudo -vvvv"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
