---
- hosts: mesos_masters
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: ansible-zookeeper
      zookeeper_hosts: "{{ mesos_master_hosts }}"

    - role: ansible-mesos
      mesos_install_mode: master
      #mesos_quorum: 2
      zookeeper_hostnames: "{{ groups.mesos_masters | join(':' + zookeeper_client_port + ',')  }}:{{ zookeeper_client_port  }}"
      mesos_hostname: "{{ ansible_default_ipv4.address }}"
      mesos_version: "{{ mesos_version }}"
      mesos_package_version: "{{ mesos_package_version }}"
    - role: ansible-java
      use_openjdk_ppa: true
      java_version: "8"
      java_register_alternative: true
    - role: ansible-role-haproxy
    - role: ansible-marathon
      zookeeper_hostnames: "{{ groups.mesos_masters | join(':' + zookeeper_client_port + ',')  }}:{{ zookeeper_client_port  }}"
      marathon_version: "{{ marathon_version }}"

- hosts: mesos_workers
  remote_user: ubuntu
  become: yes
  become_method: sudo
  roles:
    - role: ansible-docker
    - role: ansible-mesos
      mesos_install_mode: slave
      #mesos_quorum: 2
      mesos_hostname: "{{ ansible_default_ipv4.address }}"
      zookeeper_hostnames: "{{ groups.mesos_masters | join(':' + zookeeper_client_port + ',')  }}:{{ zookeeper_client_port  }}"
      mesos_containerizers: "docker,mesos"
      mesos_version: "{{ mesos_version }}"
      mesos_package_version: "{{ mesos_package_version }}"
