---
- hosts: mesos_masters
  remote_user: ubuntu
  become: yes
  become_method: sudo
  vars:
    - zookeeper_hosts_list:
      - 172.22.4.107

  roles:
    - role: ansible-zookeeper
      zookeeper_hosts: "{{ zookeeper_hosts_list }}"

    - role: ansible-mesos
      mesos_install_mode: master
      #mesos_quorum: 2
      zookeeper_hostnames: "{{ groups.mesos_masters | join(':' + zookeeper_client_port + ',')  }}:{{ zookeeper_client_port  }}"
      mesos_hostname: "{{ ansible_default_ipv4.address }}"
      mesos_version: "0.28.2"
      mesos_package_version: "2.0.27"
    - role: ansible-java
      use_openjdk_ppa: true
      java_version: "8"
      java_register_alternative: true
    - role: ansible-role-haproxy
    - role: ansible-marathon
      zookeeper_hostnames: "{{ groups.mesos_masters | join(':' + zookeeper_client_port + ',')  }}:{{ zookeeper_client_port  }}"
      marathon_version: "1.1.2"
      #marathon_apt_package: "marathon=1.1.2-1.0.482.ubuntu1404"

- hosts: mesos_workers
  remote_user: ubuntu
  become: yes
  become_method: sudo
  roles:
    - role: ansible-docker
    - role: ansible-mesos
      mesos_install_mode: slave
      #mesos_quorum: 2
      mesos_hostname: "{{ ansible_default_ipv4.address }}"
      zookeeper_hostnames: "{{ groups.mesos_masters | join(':' + zookeeper_client_port + ',')  }}:{{ zookeeper_client_port  }}"
      mesos_containerizers: "docker,mesos"
      mesos_version: "0.28.2"
      mesos_package_version: "2.0.27"
